addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-4.9
    - g++-4.9
    - clang
    - libcurl4-openssl-dev
    - libcppunit-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.8"; fi

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++
  - clang
# Build steps
script:
  - $CXX --version
  - make clean
  - make
  - make test
