sudo: false

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - build-essential
    - manpages-dev 
    - gcc-6
    - g++-6
    - clang
    - libcurl4-openssl-dev
    - libcppunit-dev
    - build-essential 
    - manpages-dev 

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++
# Build steps
script:
  - $CXX --version
  - make clean
  - make
  - make test
