addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libcurl4-openssl-dev
    - libcppunit-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

language: cpp

compiler:
  - g++

script:
  - $CXX --version
  - make clean
  - make
  - make test
  - less Http.test.xml