addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - libcurl4-openssl-dev
    - libcppunit-dev
    - build-essential 
    - manpages-dev 

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

language: cpp

compiler:
  - g++

script:
  - $CXX --version
  - make clean
  - make
