addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
    - libcurl-dev
    - libcppunit-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++
# Build steps
script:
  - $CXX --version
  - make clean
  - make
  - make test
